/**
 * Created by nihilism on 03/06/2017.
 */
var UNAUTHORIZED = 401;
var INTERNAL_ERROR = 500;
var BAD_GATEWAY = 502;
var GATEWAY_TIMEOUT = 504;
var OK = 200;
export default {
    OK: OK,
    UNAUTHORIZED: UNAUTHORIZED,
    INTERNAL_ERROR: INTERNAL_ERROR,
    BAD_GATEWAY: BAD_GATEWAY,
    GATEWAY_TIMEOUT: GATEWAY_TIMEOUT
};
